## main ##
TITLE = "AUtoDio"

GEOMETRY = "1080x720"

BUTTON_ADD = "추가"
BUTTON_DELETE = "삭제"
BUTTON_RELOAD = "새로고침"



## toplevelAdd ##
ADD_GEOMETRY = "300x400"

BUTTON_OPEN_FILE = "파일 열기"

LABEL_FILE_PATH = "파일 경로: "
LABEL_FILE_NAME = "파일명: "

LABEL_WEEK = "요일: "
CHECKBUTTON_MON = "월"
CHECKBUTTON_TUE = "화"
CHECKBUTTON_WED = "수"
CHECKBUTTON_THU = "목"
CHECKBUTTON_FRI = "금"

LABEL_TIME = "시간: "
COMBOBOX_HOUR = list(range(24))
LABEL_HOUR = "시"
COMBOBOX_MINUTE = list(range(60))
LABEL_MINUTE = "분"
COMBOBOX_WIDTH = 3