## main ##
TITLE = "AUtoDio Ver 0.1.1"

GEOMETRY = "1600x900"

BUTTON_ADD = "추가"
BUTTON_DELETE = "삭제"
BUTTON_RELOAD = "새로고침"
BUTTON_EXIT = "끝내기"

LABEL_RECORD_TITLE = ["번호", "파일명", "파일 경로", "볼륨", "요일", "시/분/초", "재생", "수정", "삭제"]
LABEL_RECORD_TITLE_WIDTH = [5, 50, 80, 8, 16, 10, 8, 8, 8]
LABEL_RECORD_FILE_NAME_WRAPLENGTH = 300
LABEL_RECORD_FILE_PATH_WRAPLENGTH = 500



## 메뉴 바 ##
MENU_FLIE = "파일"
MENU_FLIE_ADD = "추가"
MENU_FLIE_EXIT = "끝내기"

MENU_PROBLEM = "문제 해결"
MENU_PROBLEM_REROAD = "새로고침"
MENU_PROBLEM_INITIALIZATION = "초기화"



## toplevelAdd ##
ADD_GEOMETRY = "300x400"

BUTTON_OPEN_FILE = "파일 열기"

LABEL_FILE_PATH = "파일 경로: "
LABEL_FILE_NAME = "파일명: "

LABEL_VOLUME = "볼륨: "
BUTTON_PLAY = "재생"
BUTTON_STOP = "정지"

LABEL_WEEK = "요일: "
CHECKBUTTON_MON = "월"
CHECKBUTTON_TUE = "화"
CHECKBUTTON_WED = "수"
CHECKBUTTON_THU = "목"
CHECKBUTTON_FRI = "금"

LABEL_TIME = "시간: "
COMBOBOX_HOUR = list(range(24))
LABEL_HOUR = "시 "
COMBOBOX_MINUTE = list(range(60))
LABEL_MINUTE = "분 "
COMBOBOX_SECOND = list(range(60))
LABEL_SECOND = "초 "
COMBOBOX_WIDTH = 3

FILE_NAME_TITLE_WIDTH = 9
FILE_NAME_WRAPLENGTH = 220



## toplevelModify ##
MODIFY_GEOMETRY = "300x250"

BUTTON_MODIFY = "수정"